server:
  port: 8081

spring:
  application:
    name: booker
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

api:
  management:
    header: "X-MANAGEMENT-API"
    key: "BOOKER"
  internal:
    header: "X-INTERNAL-API"
    services:
      gandalf: "GANDALF_INTERNAL_KEY"
      okarun: "OKARUN_INTERNAL_KEY"

grpc:
  client:
    gandalf:
      address: localhost:9098
      negotiation-type: plaintext

minio:
  authorBucket: author
  bookBucket: book
  url: http://localhost:19000
  access_key: booker
  secret_key: yaponimaybookera

jobs:
  reservationCheck:
    cron: "0/20 * * * * ?"
    enabled: true

kafka:
  topics:
    notification:
      destination: okarun.notifications
  clusters:
    default:
      bootstrap-servers:
        - localhost:29092
      properties:
        acks: -1
        delivery.timeout.ms: 90000
        batch.size: 10240
        linger.ms: 100
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
      producer:
        client-id: liljarn.gandalf
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      security:
        protocol: PLAINTEXT
