server:
  port: 8081

spring:
  application:
    name: booker
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

api:
  management:
    key: "BOOKER"

grpc:
  client:
    gandalf:
      address: localhost:9098
      negotiation-type: plaintext

minio:
  authorBucket: author
  bookBucket: book
  url: http://localhost:19000
  access_key: booker
  secret_key: yaponimaybookera

jobs:
  reservationCheck:
    cron: "0 0 0 * * ?"
    enabled: true

kafka:
  properties:
    bootstrapServer: localhost:29092

  topics:
    notification:
      destination: okarun.notifications
