server:
  port: 8081

spring:
  application:
    name: booker
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

grpc:
  client:
    gandalf:
      address: localhost:9098
      negotiation-type: plaintext
